[package]
name = "stratmat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.0", default-features = false, features = ["animation", "bevy_animation", "bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_render", "bevy_scene", "bevy_sprite", "bevy_text", "bevy_ui", "bevy_winit", "default_font", "jpeg", "multi-threaded", "serialize", "subpixel_glyph_atlas", "png", "trace", "webgl2", "x11", "webp"] }
bevy-inspector-egui = "0.22.1" 
bevy-trait-query = "0.4.0"
bevy_commandify = "0.2.0"
bevy_egui = "0.24.0"
bevy_eventlistener_core = "0.6.2"
bevy_mod_debugdump = "0.9.0"
bevy_mod_picking = { version = "0.17.0", features = ["backend_egui"] }
bevy_picking_core = "0.17.0"
bevy_vector_shapes = "0.6.0"
chrono = "0.4.31"
clap = { version = "4.4.18", features = ["derive", "env"] }
derive_more = { version = "0.99.17", features = ["from"], default-features = false }
enum-iterator = "1.5.0"
eyre = "0.6.12"
float_eq = "1.0.1"
int-enum = "1.0.0"
itertools = "0.12.0"
log = "0.4.20"
ron = "0.8.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.56"
tracing = "0.1.40"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
