merge_derives = false
use_field_init_shorthand = true

# Unstable options that might be nice someday

blank_lines_upper_bound = 2
comment_width = 100
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
overflow_delimited_expr = true
# wrap_comments = true