name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build wasm
      run: cargo build --verbose --target wasm32-unknown-unknown
    - name: Test
      run: cargo test --verbose
    - name: Test wasm
      run: cargo test --verbose --target wasm32-unknown-unknown
