name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --all --verbose
    - name: Test
      run: cargo test --all --verbose

  build-wasm:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    env: 
      RUSTFLAGS: "--cfg=web_sys_unstable_apis"
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install Target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --all --verbose --target wasm32-unknown-unknown

  build-wasm-dom:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    env: 
      RUSTFLAGS: "--cfg=web_sys_unstable_apis"
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install Target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --all --verbose --target wasm32-unknown-unknown --no-default-features --features dom

  build-release-wasm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env: 
      RUSTFLAGS: "--cfg=web_sys_unstable_apis"
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install Target
      run: rustup target add wasm32-unknown-unknown
    - name: Install Bindgen
      uses: jetli/wasm-bindgen-action@v0.2.0
    - name: Build
      run: cargo build --profile release-size --target wasm32-unknown-unknown
    - name: Upload Stratmat Package
      uses: actions/upload-artifact@v4
      with:
        name: stratmat.wasm
        path: target/wasm32-unknown-unknown/stratmat.wasm

  build-release-wasm-dom:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env: 
      RUSTFLAGS: "--cfg=web_sys_unstable_apis"
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "cargo"
    - name: Install Target
      run: rustup target add wasm32-unknown-unknown
    - name: Build 
      run: cargo build --profile release-size --target wasm32-unknown-unknown --no-default-features --features dom
    - name: Rename output
      run: mv target/wasm32-unknown-unknown/stratmat.wasm target/wasm32-unknown-unknown/stratmat_components.wasm
    - name: Upload Stratmat Components Package
      uses: actions/upload-artifact@v4
      with:
        name: stratmat.wasm
        path: target/wasm32-unknown-unknown/stratmat_components.wasm

  package-release:
    needs: 
    - build-release-wasm
    - build-release-wasm-dom
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Download Stratmat Package
      uses: actions/download-artifact@v4
      with:
        path: public
        name: stratmat.wasm
    - name: Download Stratmat Components Package
      uses: actions/download-artifact@v4
      with:
        path: public
        name: stratmat_components.wasm
    - name: Run Bindgen
      run: wasm-bindgen --target web --no-typescript --out-dir public/static/app --out-name stratmat stratmat.wasm
    - name: Run Bindgen DOM
      run: wasm-bindgen --target web --no-typescript --out-dir public/static/app --out-name stratmat_components stratmat_components.wasm
    - name: Optimise Wasm
      uses: NiklasEi/wasm-opt-action@v2
      with:
        file: public/static/app/stratmat_bg.wasm
    - name: Optimise Wasm DOM
      uses: NiklasEi/wasm-opt-action@v2
      with:
        file: public/static/app/stratmat_components_bg.wasm
    - name: Tataru
      run: cargo run --package tataru -- --all
    - name: Copy Assets to public/
      run: cp -r assets public/static/app
    - name: Upload Release Package
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: public
        include-hidden-files: true

  deploy-gh-pages:
    needs: 
    - package-release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Download Release Package
      uses: actions/download-artifact@v4
      with:
        path: public
        name: release-package
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        build_dir: public
        fqdn: stratmat.dynamis.gg
        jekyll: false
              